spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.5:3306/kspia_mtd_op?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: kspia01!@#
  jpa:
   show-sql: true
   hibernate:
    ddl-auto: update
   properties:
    hibernate:
      format_sql: true

token:
  expiration_time: 864000000
  secret: user_token_native_user_service_default

gateway:
  ip: 192.168.10.81
  # ip: 172.30.1.49

order_service:
 url: http://ORDER-SERVICE/order-service/%s/orders
 exception:
  orders_is_empty: User's orders is empty.
